remote_theme: aljazceru/hacker-gh-pages-theme
plugins:
- jekyll-remote-theme

show_downloads: false
google_analytics: G-6DPY5RBB5L
plausible_script_url: https://analytics.cypherpunk.cloud/js/script.js
plausible: dlc.wiki
